### ISSUE TITLE
Scalar layer interfere with default Pixi mesh renderer

### ISSUE THREAD

**Issue by claustres** [weacast/weacast-leaflet#5]
### Steps to reproduce

Display a Weacast scalar layer then a standard Pixi mesh in an app, the standard Pixi mesh disappea and the following error message is raised: `[.WebGL-0000023C042FCA30]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 1`

Linked to the fact the grid renderer should not modify the mesh renderer prototype [here](https://github.com/weacast/weacast-leaflet/blob/master/src/grid-renderer.js#L78)

**Comment by cnouguier** [comment]
Best solution seems to migrate to Pixi.js 5 because the new version allows to render colored mesh.
